name: Testing
language: python
env:
  - CODECOV_TOKEN='18a8beea-4407-498f-8b15-990517519ac2'
os:
  - linux
python:
  - "3.6"      # current default Python on Travis CI
  - "3.7"
  - "3.8"
  - "3.9"
  - "3.9-dev"  # 3.9 development branch
  - "nightly"  # nightly build
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install requests
script:
  - flask run
  - sleep 5
  - python -m unittest test
